resources:
- ../base

namespace: monitoring

configMapGenerator:
- literals:
  - RABBITMQ_HOSTS=node001.rmq.cset.int.gdcorp.tools:15672,node002.rmq.cset.int.gdcorp.tools:15672,node003.rmq.cset.int.gdcorp.tools:15672
  name: env-specific-values
