userdata_deploymentserver: |
  #cloud-config
  runcmd:
    - godaddy-ad-groups-sudo admins_infosec-dcu
userdata: |
        #cloud-config
        runcmd:
          - godaddy-ad-groups-sudo admins_infosec-dcu
        users:
          - name: {{ lookup('amazon.aws.aws_secret', '/Secrets/openstack/creds', bypath=true)['/Secrets/openstack/creds'] | from_json | json_query('user')}}
            shell: /bin/bash
            groups: wheel
            lock_passwd: false
            passwd: {{ lookup('amazon.aws.aws_secret', '/Secrets/openstack/creds', bypath=true)['/Secrets/openstack/creds'] | from_json | json_query('password') | password_hash('sha512') }}
        package_upgrade: true
openstack:
  dev:
    prefix: p3dl
    mongo:
      flavor: c4.r8.d100
    k3s:
      ncm_ips:
        k3sagent: "10.37.81.87"
        k3sserver: "10.37.81.90"
      nodes:
        - { zonename: k3sserver, flavor: c4.r8.d100, k3srole: server, name: "svr001"}
        - { zonename: k3sserver, flavor: c4.r8.d100, k3srole: server, name: "svr002"}
        - { zonename: k3sserver, flavor: c4.r8.d100, k3srole: server, name: "svr003"}
        - { zonename: k3sagent1, flavor: c4.r8.d100, k3srole: agent, name: "agt001"}
        - { zonename: k3sagent1, flavor: c4.r8.d100, k3srole: agent, name: "agt002"}
        - { zonename: k3sagent1, flavor: c4.r8.d100, k3srole: agent, name: "agt003"}
        - { zonename: k3sagent2, flavor: c4.r8.d100, k3srole: agent, name: "agt004"}
        - { zonename: k3sagent2, flavor: c4.r8.d100, k3srole: agent, name: "agt005"}
        - { zonename: k3sagent2, flavor: c4.r8.d100, k3srole: agent, name: "agt006"}
        - { zonename: k3sagent2, flavor: c8.r24.d250, k3srole: agent, name: "agt007"}
    rabbitmq:
      nodes:
        - { zonename: rabbitmqservers, flavor: c4.r8.d100, name: "svr001"}
        - { zonename: rabbitmqservers, flavor: c4.r8.d100, name: "svr002"}
        - { zonename: rabbitmqservers, flavor: c4.r8.d100, name: "svr003"}
  prod:
    prefix: p3pl
    k3s:
      ncm_ips:
        k3sagent: "10.37.81.112"
        k3sserver: "10.37.81.113"
      nodes:
        - { zonename: k3sserver, flavor: c8.r16.d200, k3srole: server, name: "svr001"}
        - { zonename: k3sserver, flavor: c8.r16.d200, k3srole: server, name: "svr002"}
        - { zonename: k3sserver, flavor: c8.r16.d200, k3srole: server, name: "svr003"}
        - { zonename: k3sagent1, flavor: c8.r16.d200, k3srole: agent, name: "agt001"}
        - { zonename: k3sagent1, flavor: c8.r16.d200, k3srole: agent, name: "agt002"}
        - { zonename: k3sagent1, flavor: c8.r16.d200, k3srole: agent, name: "agt003"}
        - { zonename: k3sagent2, flavor: c8.r16.d200, k3srole: agent, name: "agt004"}
        - { zonename: k3sagent2, flavor: c8.r16.d200, k3srole: agent, name: "agt005"}
        - { zonename: k3sagent2, flavor: c8.r16.d200, k3srole: agent, name: "agt006"}
        - { zonename: k3sagent3, flavor: c8.r16.d200, k3srole: agent, name: "agt007"}
        - { zonename: k3sagent3, flavor: c8.r16.d200, k3srole: agent, name: "agt008"}
        - { zonename: k3sagent3, flavor: c8.r16.d200, k3srole: agent, name: "agt009"}
        - { zonename: k3sagent4, flavor: c8.r16.d200, k3srole: agent, name: "agt010"}
        - { zonename: k3sagent4, flavor: c8.r16.d200, k3srole: agent, name: "agt011"}
        - { zonename: k3sagent4, flavor: c12.r32.d300, k3srole: agent, name: "agt012"}
    rabbitmq:
      nodes:
        - { zonename: rabbitmqservers, flavor: c6.r12.d150, name: "svr001"}
        - { zonename: rabbitmqservers, flavor: c6.r12.d150, name: "svr002"}
        - { zonename: rabbitmqservers, flavor: c6.r12.d150, name: "svr003"}
