- module: system
  period: 20s
  metricsets:
    - cpu
    - load
    - memory
    - network
    - process
    - process_summary
  processes: ['.*']
  process.include_top_n:
    by_cpu: 5      # include top 5 processes by CPU
    by_memory: 5   # include top 5 processes by memory
- module: system
  period: 1m
  metricsets:
    - filesystem
  filesystem.ignore_types: [nfs, smbfs, autofs, proc, tmpfs, devpts, sysfs, cgroup, devpts, mqueue, overlay]
