---
- name: Install MongoDB 3.6 Repo
  ansible.builtin.yum_repository:
    name: mongodb
    baseurl: https://repo.mongodb.org/yum/redhat/$releasever/mongodb-org/3.6/x86_64/
    enabled: yes
    gpgcheck: yes
    gpgkey: https://www.mongodb.org/static/pgp/server-3.6.asc
    description: MongoDB 3.6 Repo
- name: Install MongoDB base package
  ansible.builtin.dnf:
    name: mongodb-org == 3.6.23
    state: present
- name: Install MongoDB server
  ansible.builtin.dnf:
    name: mongodb-org-server == 3.6.23
    state: present
- name: Install MongoDB shell
  ansible.builtin.dnf:
    name: mongodb-org-shell == 3.6.23
    state: present
- name: Install MongoDB mongos
  ansible.builtin.dnf:
    name: mongodb-org-mongos == 3.6.23
    state: present
- name: Install MongoDB mongos
  ansible.builtin.dnf:
    name: mongodb-org-tools == 3.6.23
    state: present
- name: Version lock mongo packages
  community.general.dnf_versionlock:
    name:
      - mongodb-org
      - mongodb-org-server
      - mongodb-org-shell
      - mongodb-org-mongos
      - mongodb-org-tools
    state: present
- name: Copy bundle to mongo-ca
  ansible.builtin.copy:
    src: /etc/ssl/certs/ca-bundle.crt
    dest: /etc/mongo-ca.pem
    owner: root
    group: mongod
    mode: 0660
    remote_src: yes
- name: Insert chain into file
  ansible.builtin.blockinfile:
    block: "{{ mongo[env].chain }}"
    path: /etc/mongo-ca.pem
- name: Copy remote mongo.pem 
  ansible.builtin.template:
    src: templates/mongo.pem.j2
    dest: /etc/mongo.pem
    owner: root
    group: mongod
    mode: 0660
- name: Copy local only mongod config
  ansible.builtin.template:
    src: mongod.local.conf.j2
    dest: /etc/mongod.conf
    owner: root
    group: root
    mode: 0644
- name: Enable service mongod
  ansible.builtin.systemd:
    name: mongod
    enabled: yes
    masked: no
    daemon_reload: yes
    state: restarted
- name: Install pymongo
  ansible.builtin.pip:
    name: pymongo
- name: Create mongo admin user
  community.mongodb.mongodb_user:
    database: admin
    name: "{{ lookup('amazon.aws.aws_secret', '/KeePass/MongoDB/phishstory/dev/superAdmin', bypath=true)['/KeePass/MongoDB/phishstory/dev/superAdmin'] | from_json | json_query('username') }}"
    password: "{{ lookup('amazon.aws.aws_secret', '/KeePass/MongoDB/phishstory/dev/superAdmin', bypath=true)['/KeePass/MongoDB/phishstory/dev/superAdmin'] | from_json | json_query('password') }}"
    state: present
    roles:
      - dbAdminAnyDatabase
      - userAdminAnyDatabase
      - readWriteAnyDatabase
- name: Copy remote mongod config
  ansible.builtin.template:
    src: mongod.remote.conf.j2
    dest: /etc/mongod.conf
    owner: root
    group: root
    mode: 0644
- name: Enable service mongod
  ansible.builtin.systemd:
    name: mongod
    enabled: yes
    masked: no
    daemon_reload: yes
    state: restarted