---
ansible_user: "{{ lookup('amazon.aws.aws_secret', '/Secrets/openstack/creds', bypath=true)['/Secrets/openstack/creds'] | from_json | json_query('user')}}"
ansible_ssh_pass: "{{ lookup('amazon.aws.aws_secret', '/Secrets/openstack/creds', bypath=true)['/Secrets/openstack/creds'] | from_json | json_query('password')}}"
ansible_become_pass: "{{ lookup('amazon.aws.aws_secret', '/Secrets/openstack/creds', bypath=true)['/Secrets/openstack/creds'] | from_json | json_query('password')}}"

kernelcare:
  key: "{{ lookup('amazon.aws.aws_secret', '/Secrets/kernelcare', bypath=true)['/Secrets/kernelcare'] | from_json | json_query(env)}}"
  dev:
    delay: 12h
  prod:
    delay: 48h

k3s:
  mysql_url: "{{ lookup('amazon.aws.aws_secret', '/Secrets/k3s-config', bypath=true)['/Secrets/k3s-config'] | from_json | json_query(env + '.url')}}"
  token: "{{ lookup('amazon.aws.aws_secret', '/Secrets/k3s-config', bypath=true)['/Secrets/k3s-config'] | from_json | json_query(env + '.token')}}"
  dev:
    version: v1.24.4+k3s1
    ncm_ips:
      k3sagent: "10.37.81.87"
      k3sserver: "10.37.81.90"
    ncm_hosts:
      k3sserver: proxy.dcu-k8s.phx3.int.dev-godaddy.com
      k3sagent: ingress.dcu-k8s.phx3.int.dev-godaddy.com
  prod:
    version: v1.24.4+k3s1
    ncm_ips:
      k3sagent: "10.37.81.112"
      k3sserver: "10.37.81.113"
    ncm_hosts:
      k3sserver: proxy.dcu-k8s.phx3.int.godaddy.com
      k3sagent: ingress.dcu-k8s.phx3.int.godaddy.com

rabbitmq:
  dev:
    domain: dev-gdcorp.tools
    ca: "{{ lookup('amazon.aws.aws_secret', '_.rmq.cset.int.dev-gdcorp.tools', bypath=true)['_.rmq.cset.int.dev-gdcorp.tools'] | from_json | json_query('chain')}}"
    cert: "{{ lookup('amazon.aws.aws_secret', '_.rmq.cset.int.dev-gdcorp.tools', bypath=true)['_.rmq.cset.int.dev-gdcorp.tools'] | from_json | json_query('crt')}}"
    key: "{{ lookup('amazon.aws.aws_secret', '_.rmq.cset.int.dev-gdcorp.tools', bypath=true)['_.rmq.cset.int.dev-gdcorp.tools'] | from_json | json_query('key')}}"
  cookie: "{{ lookup('amazon.aws.aws_secret', '/Secrets/rmq-cookie', bypath=true)['/Secrets/rmq-cookie'] | from_json | json_query(env)}}"

mongo:
  dev:
    chain: "{{ lookup('amazon.aws.aws_secret', 'mongodb.cset.int.dev-gdcorp.tools', bypath=true)['mongodb.cset.int.dev-gdcorp.tools'] | from_json | json_query('chain')}}"
    key: "{{ lookup('amazon.aws.aws_secret', 'mongodb.cset.int.dev-gdcorp.tools', bypath=true)['mongodb.cset.int.dev-gdcorp.tools'] | from_json | json_query('key')}}"
    crt: "{{ lookup('amazon.aws.aws_secret', 'mongodb.cset.int.dev-gdcorp.tools', bypath=true)['mongodb.cset.int.dev-gdcorp.tools'] | from_json | json_query('crt')}}"