---
ansible_user: "{{ lookup('amazon.aws.aws_secret', '/Secrets/openstack/creds', bypath=true)['/Secrets/openstack/creds'] | from_json | json_query('user')}}"
ansible_ssh_pass: "{{ lookup('amazon.aws.aws_secret', '/Secrets/openstack/creds', bypath=true)['/Secrets/openstack/creds'] | from_json | json_query('password')}}"
ansible_become_pass: "{{ lookup('amazon.aws.aws_secret', '/Secrets/openstack/creds', bypath=true)['/Secrets/openstack/creds'] | from_json | json_query('password')}}"

kernelcare:
  key: "{{ lookup('amazon.aws.aws_secret', '/Secrets/kernelcare', bypath=true)['/Secrets/kernelcare'] | from_json | json_query(env)}}"
  dev:
    delay: 12h
  prod:
    delay: 48h

k3s:
  mysql_url: "{{ lookup('amazon.aws.aws_secret', '/Secrets/k3s-config', bypath=true)['/Secrets/k3s-config'] | from_json | json_query('url')}}"
  token: "{{ lookup('amazon.aws.aws_secret', '/Secrets/k3s-config', bypath=true)['/Secrets/k3s-config'] | from_json | json_query('token')}}"
  dev:
    version: v1.24.4+k3s1
    ncm_ips:
      k3sagent: "10.37.81.87"
      k3sserver: "10.37.81.90"
    ncm_hosts:
      k3sserver: proxy.dcu-k8s.phx3.int.dev-godaddy.com
      k3sagent: ingress.dcu-k8s.phx3.int.dev-godaddy.com
