apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: product-security
resources:
- ./namespace.yml
- ./deployment.yml
- ./service.yml
images:
- name: gdartifactory1.jfrog.io/docker-dcu-local/auth-proxy
  newTag: prod
