apiVersion: v1
clusters:
- cluster:
    certificate-authority: p3pabuse01-ca.pem
    server: https://proxy.dcu-k8s.phx3.int.godaddy.com:443
  name: prod
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJlRENDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdGMyVnkKZG1WeUxXTmhRREUyTmpNM05qRXpPRGN3SGhjTk1qSXdPVEl4TVRFMU5qSTNXaGNOTXpJd09URTRNVEUxTmpJMwpXakFqTVNFd0h3WURWUVFEREJock0zTXRjMlZ5ZG1WeUxXTmhRREUyTmpNM05qRXpPRGN3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFTNGtwaHdaVklEVjJPM2Q3MU41aFhIVmxJRGdHT0tYS0NxaDIyY1N6eksKOHdrcDEwYTBtUHBzcURHSkZuZ3BxTFppa2hMWjR5blJSWU1iWmlydUcrb0JvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVW9kSjN1eUxjTU1GM3F6WUNSNytGCjZSVWxJNXd3Q2dZSUtvWkl6ajBFQXdJRFNRQXdSZ0loQUpwQmJrOVZJY1RRcGNKVkVQK1lGbUZzOC90WkxwQVoKbXp5WTFwaTdpMTkrQWlFQXRjTXY4OEYrSjAzS2VTM3NMRW5nOVVhTkZmYktwRGE3cFViU1NpS1RLK2M9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://10.37.81.90:6443
  name: dev
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJkekNDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdGMyVnkKZG1WeUxXTmhRREUyTmprNU1EYzFOVGN3SGhjTk1qSXhNakF4TVRVeE1qTTNXaGNOTXpJeE1USTRNVFV4TWpNMwpXakFqTVNFd0h3WURWUVFEREJock0zTXRjMlZ5ZG1WeUxXTmhRREUyTmprNU1EYzFOVGN3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFSN1Zhc3hZZHJubi9XYXZMbmlnNDJMa2tRVmZYSEpCRFovZFE5aEswMXQKeTJZazNFU2FHWTZnOG1UanlFRVQzVThyWHk2bnpLRm1PSE80SENucTJlRDlvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVVJRM0VuT240Q1ZsU2Y4Q1VqRko2Cm03UlN2cUl3Q2dZSUtvWkl6ajBFQXdJRFNBQXdSUUloQUlzQkpXKzVqYnlyZ0xYNXFoaldvQlRueXFtQlV5Vk8KdDZUTVRiREpSeUk1QWlBMGMyRldiUEZjRTNOZXZMUDZYRE0zMDljRk0weTJlb2lpWWJLR2c2Vzd1QT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://proxy.dcu-k8s.phx3.int.godaddy.com:6443
  name: prod-ng
contexts:
- context:
    cluster: dev
    namespace: abuse-api-dev
    user: p3dabuse01-admin
  name: dev
- context:
    cluster: dev
    namespace: abuse-api-dev
    user: p3dabuse01-admin
  name: dev-dcu
- context:
    cluster: dev
    namespace: abuse-api-dev
    user: p3dabuse01-admin
  name: dev-cset
- context:
    cluster: dev
    namespace: abuse-api-test
    user: p3dabuse01-admin
  name: test
- context:
    cluster: dev
    namespace: abuse-api-test
    user: p3dabuse01-admin
  name: test-dcu
- context:
    cluster: dev
    namespace: abuse-api-test
    user: p3dabuse01-admin
  name: test-cset
- context:
    cluster: prod
    namespace: abuse-api-prod
    user: p3pabuse01-admin
  name: prod
- context:
    cluster: prod
    namespace: abuse-api-prod
    user: p3pabuse01-admin
  name: prod-dcu
- context:
    cluster: prod
    namespace: abuse-api-ote
    user: p3pabuse01-admin
  name: ote
- context:
    cluster: prod
    namespace: abuse-api-ote
    user: p3pabuse01-admin
  name: ote-dcu
- context:
    cluster: prod-ng
    namespace: abuse-api-ote
    user: prod-cset
  name: ote-cset
- context:
    cluster: prod-ng
    namespace: abuse-api-prod
    user: prod-cset
  name: prod-cset
current-context: dev
kind: Config
preferences: {}
users:
- name: p3dabuse01-admin
  user:
    client-certificate: dev-ng-client.crt
    client-key: dev-ng-client.key
- name: p3pabuse01-admin
  user:
    client-certificate: p3pabuse01-client.crt
    client-key: p3pabuse01-client.key
- name: prod-cset
  user:
    client-certificate: prod-ng-client.crt
    client-key: prod-ng-client.key
