name: Create Action Runners
project_code: abuse-pipeline-cicd
region: us-west-2
template_path: gha-runner.yaml
parameters:
  IsOrgRunner: "true"
  ProductVersion: 2.3.1
  RunnerName: github-actions-runner
  RunnerLabels: self-hosted,csetubuntu
  RunnerAutoScalingGroupDesiredSize: "1"
  RunnerVolumeSize: "100"
  RunnerInstanceType: t3.small
  GitHubOrganization: gdcorp-infosec
  GitHubSecretName: /GitHub/OrgRunnerPAT
  RunnerAutoScalingGroupWarmPoolSize: "0"
  RunnerAutoScalingGroupSubnets: /AdminParams/VPC/DXAPPSubnets
  RunnerGroupName: cset-runners
  RunnerAMIId: /GoldenAMI/gd-ubuntu20.04-runner/latest
  DeviceName: /dev/sda1
  UseCICDRole: "true"
  CustomUserData: echo "$(dig +short phx-prd.openstack.int.gd3p.tools | tail -n1) phx.openstack.int.gd3p.tools" | tee -a /etc/hosts
