apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-action-runner-manager
  namespace: cicd
  labels:
    app: github-action-runner-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: github-action-runner-manager
  template:
    metadata:
      labels:
        app: github-action-runner-manager
    spec:
      serviceAccountName: cicd-account
      imagePullSecrets:
        - name: dcu-artifactory-creds
      containers:
        - name: manager
          imagePullPolicy: "Always"
          image: docker-dcu-local.artifactory.secureserver.net/cset-action-manager:latest
          env:
            - name: GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: github-pat
                  key: pat