apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cicd-account
  namespace: cicd
rules:
  - apiGroups: ["apps"]
    resources:
      - deployments
      - deployments/scale
    verbs:
      - get
      - update
      - patch
      - create
  - apiGroups: [""]
    resources:
      - pods
    verbs:
      - get
      - list
  - apiGroups: [""]
    resources:
      - secrets
    verbs:
      - delete
      - create