---
- name: rabbitmq_erlang
  ansible.builtin.yum_repository:
    name: rabbitmq_erlang
    baseurl: https://packagecloud.io/rabbitmq/erlang/el/8/$basearch
    gpgcheck: yes
    enabled: yes
    description: RabbitMQ Erlang
    gpgkey:
      - https://packagecloud.io/rabbitmq/erlang/gpgkey
      - https://github.com/rabbitmq/signing-keys/releases/download/2.0/rabbitmq-release-signing-key.asc
- name: rabbitmq_server
  ansible.builtin.yum_repository:
    name: rabbitmq_server
    baseurl: https://packagecloud.io/rabbitmq/rabbitmq-server/el/8/$basearch
    gpgcheck: yes
    enabled: yes
    description: RabbitMQ server
    gpgkey:
      - https://packagecloud.io/rabbitmq/rabbitmq-server/gpgkey
      - https://github.com/rabbitmq/signing-keys/releases/download/2.0/rabbitmq-release-signing-key.asc
- name: Install erlang base package
  dnf:
    name: erlang == 24.2.2-1.el8
    state: present
- name: Install socat base package
  dnf:
    name: socat
    state: present
- name: Install rabbitmq-server base package
  dnf:
    name: rabbitmq-server == 3.9.8-1.el8
    state: present

- name: Version lock rabbitmq packages
  community.general.dnf_versionlock:
    name:
      - rabbitmq-server
      - socat
      - erlang
    state: present

- name: Copy remote rabbitmq-env.conf config
  template:
    src: templates/rabbitmq-env.conf.j2
    dest: /etc/rabbitmq/rabbitmq-env.conf
    owner: root
    group: rabbitmq
    mode: 0644

- name: Copy remote rabbitmq.conf config
  template:
    src: templates/rabbitmq.conf.j2
    dest: /etc/rabbitmq/rabbitmq.conf
    owner: root
    group: rabbitmq
    mode: 0644

- name: Copy remote enabled_plugins config
  template:
    src: files/enabled_plugins
    dest: /etc/rabbitmq/enabled_plugins
    owner: root
    group: rabbitmq
    mode: 0644

- name: Create limits directory
  file:
    path: /etc/systemd/system/rabbitmq-server.service.d/
    state: directory
    mode: 0644
    owner: root
    group: root
- name: Copy remote limits.conf config
  template:
    src: files/limits.conf
    dest: /etc/systemd/system/rabbitmq-server.service.d/limits.conf
    owner: root
    group: root
    mode: 0644

- name: Copy remote ca.crt config
  template:
    src: templates/ca.crt.j2
    dest: /etc/rabbitmq/ca.crt
    owner: root
    group: rabbitmq
    mode: 0660

- name: Copy remote rmq.crt config
  template:
    src: templates/rmq.crt.j2
    dest: /etc/rabbitmq/rmq.crt
    owner: root
    group: rabbitmq
    mode: 0660

- name: Copy remote rmq.key config
  template:
    src: templates/rmq.key.j2
    dest: /etc/rabbitmq/rmq.key
    owner: root
    group: rabbitmq
    mode: 0660

- name: Copy remote erlang.cookie config
  template:
    src: templates/erlang.cookie.j2
    dest: /var/lib/rabbitmq/.erlang.cookie
    owner: rabbitmq
    group: rabbitmq
    mode: 0400

