{
 "title": "Fluentd",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "datasource", "label": "Cluster", "query": "prometheus" },
   { "name": "tag", "label": "tag", "query": { "query": "label_values(tag)" } }
  ]
 },
 "panels": [
  {
   "title": "Fluentd Containers Running",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running{namespace=~\"fluentd.*\"}) by (namespace, container)",
     "legendFormat": "{{ container }}"
    }
   ]
  },
  {
   "title": "Input /  output rate",
   "type": "graph",
   "description": "Input  and output total rates",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(fluentd_input_status_num_records_total[$interval]))",
     "legendFormat": "input"
    },
    {
     "expr": "- sum(rate(fluentd_output_status_num_records_total[$interval]))",
     "legendFormat": "output"
    }
   ]
  },
  {
   "title": "Error Rates",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (type) (rate(fluentd_output_status_num_errors[$interval]))",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Ratio of available space in buffer.",
   "type": "graph",
   "description": "fluentd_output_status_buffer_available_space_ratio",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(fluentd_output_status_buffer_available_space_ratio) by (pod, type) / 1000",
     "legendFormat": "{{pod}} {{ type }}"
    }
   ]
  },
  {
   "title": "Input entries rate per hostname",
   "type": "graph",
   "description": "fluentd_input_status_num_records_total",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(fluentd_input_status_num_records_total[$interval])) by (hostname)",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Application Security Logs",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(fluentd_input_status_num_records_total{tag=~\"$tag\",tag=~\"V2.SECURITY.GEN.APP.*|SECURITY.GEN.APP.*\",service=~\"fluentd\"}[$interval])) by (tag, service)",
     "legendFormat": "{{tag}}"
    }
   ]
  },
  {
   "title": "incoming records / sec / tag - TCP",
   "type": "graph",
   "description": "This does not include application security logs",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(fluentd_input_status_num_records_total{tag=~\"$tag\",tag=~\"V2.*|SECURITY.*\",service=~\"fluentd\"}[$interval])) by (tag, service)",
     "legendFormat": "{{ service }} | {{ tag }}"
    }
   ]
  },
  {
   "title": "Outgoing Record Tags - TCP",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(fluentd_output_status_num_records_total{tag=~\"$tag\",tag=~\"V2.*|SECURITY.*\",service=~\"fluentd\"}[$interval])) by (tag, service)",
     "legendFormat": "{{ service }} | {{ tag }}"
    }
   ]
  },
  {
   "title": "incoming records / sec / tag - Public TCP",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(fluentd_input_status_num_records_total{tag=~\"$tag\",tag=~\"V2.*|SECURITY.*|OTHER.*|untagged.*\",service=~\"fluentd-public\"}[$interval])) by (tag, service)",
     "legendFormat": "{{ service }} | {{ tag }}"
    }
   ]
  },
  {
   "title": "Outgoing Record Tags - Public TCP",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(fluentd_output_status_num_records_total{tag=~\"$tag\",tag=~\"V2.*|SECURITY.*|OTHER.*|untagged.*\",service=~\"fluentd-public\"}[$interval])) by (tag, service)",
     "legendFormat": "{{ service }} | {{ tag }}"
    }
   ]
  },
  {
   "title": "incoming records / sec / tag - UDP",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(fluentd_input_status_num_records_total{tag=~\"$tag\",tag=~\"SECURITY.*\",service=~\"fluentd-udp\"}[$interval])) by (tag, service)",
     "legendFormat": "{{ service }} | {{ tag }}"
    }
   ]
  },
  {
   "title": "Outgoing Records Tags - UDP",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(fluentd_output_status_num_records_total{tag=~\"$tag\",tag=~\"SECURITY.*|system.*\",service=~\"fluentd-udp\"}[$interval])) by (tag, service)",
     "legendFormat": "{{ service }} | {{ tag }}"
    }
   ]
  },
  {
   "title": "Emit Counts",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(fluentd_output_status_emit_count{plugin_id=~\".*\"}[$interval])) by (type)",
     "legendFormat": "{{ plugin_id  }}"
    }
   ]
  },
  {
   "title": "Buffer Queue Length",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 70 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(fluentd_output_status_emit_count[$interval])) by (type, service)",
     "legendFormat": "{{ service }} | {{ type }}"
    }
   ]
  },
  {
   "title": "Fluentd POD CPU Usage ($interval avg)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 80 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"fluentd.*\"}[$interval])) by (pod)",
     "legendFormat": "pod:{{ pod }}"
    }
   ]
  },
  {
   "title": "Fleuntd POD Memory Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 80 },
   "yaxes": [
    { "format": "MBs" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{pod=~\"fluentd.*\", name=~\"^k8s_.*\"}) / 1000000",
     "legendFormat": "pod:{{ pod }}"
    }
   ]
  }
 ]
}