{
 "title": "GoWEC",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Cluster", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "GoWEC Pod CPU usage (10m avg)",
   "type": "graph",
   "description": "Average CPU usage per GoWEC Pods.\n\nCan be used to identify any abnormal behaviors to a pod when showing abnormally data pattern.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{pod=~\"gowec.*\"}[10m]))",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "GoWEC Pod memory usage",
   "type": "graph",
   "description": "GoWEC Pods' memory usage.\n\nThis graph can be used to identify any abnormal memory usage on pods.\n\nIncreasing buffer limits could result in higher memory usage.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{pod=~\"gowec.*\"}) / 1000000",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "# of Event Requests per Pod",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_pod_name)(increase(wec_server_request_counter{route=\"/wsman/subscriptions/\"}[2m]))",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "# of Events Read per Pod",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(gowec_events_received[2m])",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "/subscriptions Call Status Codes",
   "type": "graph",
   "description": "List of response Status Codes for the route \"/wsman/subscriptions/\". ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (code)(increase(wec_server_request_counter{route=\"/wsman/subscriptions/\", verb=\"POST\"}[2m]))",
     "legendFormat": "Status Code {{code}}"
    }
   ]
  },
  {
   "title": "/SubscriptionManager/WEC Status Codes",
   "type": "graph",
   "description": "Number of HTTP response status codes for route=\"/wsman/SubscriptionManager/WEC\".",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (code) (increase(wec_server_request_counter{route=\"/wsman/SubscriptionManager/WEC\"}[2m]))",
     "legendFormat": "Status Code {{code}}"
    }
   ]
  },
  {
   "title": "Max Events per S3 Object",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(gowec_max_events_per_object)"
    }
   ]
  },
  {
   "title": "# of GoWEC Pods",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (kubernetes_pod_name) (gowec_events_received))"
    }
   ]
  },
  {
   "title": "# of WEC Server Requests",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(wec_server_request_counter{route=\"/wsman/subscriptions/\"}[2m]))",
     "legendFormat": "# of requests"
    }
   ]
  },
  {
   "title": "Current WEC requests Size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(wec_server_request_sizes_sum{route=\"/wsman/subscriptions/\"}[2m])) / 1000000"
    }
   ]
  },
  {
   "title": "# of Events per Pod (Avg)",
   "type": "stat",
   "description": "Average number of events requested per pod.",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(gowec_events_received[2m])) / count(count by (kubernetes_pod_name) (gowec_events_received))"
    }
   ]
  },
  {
   "title": "# of Events Read",
   "type": "graph",
   "description": "Total number of events that were read by an aggregators across different pods at the moment.\n\nThis is emitted when an aggregator reads an Event from an EventChannel.\n\nHigh value here could indicate, GOWEC service as a whole is receiving many events.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(gowec_events_received[2m]))",
     "legendFormat": "# of Events Read"
    }
   ]
  },
  {
   "title": "# of Events Read per Hour",
   "type": "graph",
   "description": "Total number of events that were read by an aggregators across different pods.\n\nThis is emitted when an aggregator reads an Event from an EventChannel.\n\nHigh value here could indicate, GOWEC service as a whole is receiving many events per Hour.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(gowec_events_received[1h]))",
     "legendFormat": "# of Events Read"
    }
   ]
  },
  {
   "title": "# of Writes to WriteChannels",
   "type": "graph",
   "description": "Total number of writes that were due to an aggregator reaching max buffer size limit or Timed Out.\n\nThis is emitted when aggregator buffer has reached configured MaxSizeBytes or MaxBufferTime.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(gowec_event_channel_length_count[2m]))",
     "legendFormat": "# of Max Size Writes"
    },
    {
     "expr": "sum(increase(gowec_timeout_delivery[2m]))",
     "legendFormat": "# of Timed Out Writes"
    }
   ]
  },
  {
   "title": "# of Writes to WriteChannels per Hour",
   "type": "graph",
   "description": "Total number of writes that were due to an aggregator reaching max buffer size limit or Timed Out.\n\nThis is emitted when aggregator buffer has reached configured MaxSizeBytes or MaxBufferTime.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(gowec_event_channel_length_count[1h]))",
     "legendFormat": "# of Max Sized Writes"
    },
    {
     "expr": "sum(increase(gowec_timeout_delivery[1h]))",
     "legendFormat": "# of Timed Out Writes"
    }
   ]
  }
 ]
}