---
- name: Install version lock
  ansible.builtin.dnf:
    name: python3-dnf-plugin-versionlock
    state: present
- name: Disable SELinux
  ansible.posix.selinux:
    state: disabled
- name: Remove the serverspec-base package
  ansible.builtin.dnf:
    name: serverspec-base
    state: absent
    autoremove: true
- name: Remove the ruby-doc package
  ansible.builtin.dnf:
    name: ruby-doc
    state: absent
    autoremove: true
- name: Remove the rubygem-rdoc package
  ansible.builtin.dnf:
    name: rubygem-rdoc
    state: absent
    autoremove: true
- name: Remove the ruby-irb package
  ansible.builtin.dnf:
    name: ruby-irb
    state: absent
    autoremove: true
- name: Remove the rubygems package
  ansible.builtin.dnf:
    name: rubygems
    state: absent
    autoremove: true
- name: Remove the ruby package
  ansible.builtin.dnf:
    name: ruby
    state: absent
    autoremove: true
- name: Install KernelCare repo
  ansible.builtin.yum_repository:
    name: kernelcare
    baseurl: https://yum.secureserver.net/repos/upstream/prod/kernelcare/8/$basearch
    enabled: yes
    gpgcheck: no
    description: kernelcare
- name: Install kernelcare
  ansible.builtin.dnf:
    name: kernelcare
    state: present
- name: Install kernelcare-selinux
  ansible.builtin.dnf:
    name: kernelcare-selinux
    state: present
- name: Install kcare config
  ansible.builtin.template:
    src: kcare.conf.j2
    dest: /etc/sysconfig/kcare/kcare.conf
    owner: root
    group: root
    mode: 0644
- name: Register kernelcare
  ansible.builtin.command: "kcarectl --register {{ kernelcare.key }}"
- name: Enable kernelcare auto-updates
  ansible.builtin.command: libcare-cron init