#!/usr/bin/env ansible-playbook
- import_playbook: openstack/mongo.yaml
  when: env == "dev"
  tags:
    - mongo

- import_playbook: openstack/k3s.yaml
  tags:
    - k3s

- import_playbook: openstack/inventory.yaml
  tags:
    - mongo
    - k3s

- import_playbook: services/mongo.yaml
  when: env == "dev"
  tags:
    - mongo

- import_playbook: services/k3s.yaml
  tags:
    - k3s
