#!/usr/bin/env ansible-playbook
- import_playbook: openstack/mongo.yaml
  when: env == "dev"
  tags:
    - mongo

- import_playbook: openstack/k3s.yaml
  tags:
    - k3s
- import_playbook: openstack/rabbitmq.yaml
  tags:
    - rabbitmq

- import_playbook: openstack/inventory.yaml
  tags:
    - mongo
    - k3s
    - rabbitmq

- import_playbook: services/mongo.yaml
  when: env == "dev"
  tags:
    - mongo

- import_playbook: services/k3s.yaml
  tags:
    - k3s

- import_playbook: services/rabbitmq.yaml
  tags:
    - rabbitmq
