apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: db-phishstory-backup
  namespace: abuse-api-prod
  labels:
    app: db-phishstory-backup
spec:
  schedule: "59  21  *  *  *"
  # Deadline in seconds for starting the job if it misses its scheduled time.
  startingDeadlineSeconds: 60
  # The cron job does not allow concurrent runs
  # if it is time for a new job run and the previous job run hasn't finished yet, the cron job skips the new job run
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      activeDeadlineSeconds: 6600
      template:
        metadata:
          labels:
            app: db-phishstory-backup
        spec:
          restartPolicy: OnFailure
          imagePullSecrets:
            - name: artifactory-saas-creds
          containers:
            - name: backup
              imagePullPolicy: Always
              image: REPLACE_WITH_GIT_COMMIT
              env:
                - name: BUILD_DATE
                  value: THIS_STRING_IS_REPLACED_DURING_BUILD
                - name: BACKUP_DEST
                  value: /backup/phishstory
                - name: BACKUP_DB
                  value: phishstory
                - name: COLLECTIONS
                  value: acknowledge_email blacklist classifier-celery crm_alerts incidents infractions jobs journal logs
                - name: APP_SLACK_WEBHOOK
                  valueFrom:
                    secretKeyRef:
                      name: db-backup-slack
                      key: handler
                - name: USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: phish-mongo-admin
                      key: username
                - name: PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: phish-mongo-admin
                      key: password
              volumeMounts:
                - mountPath: /backup
                  name: nfs-persistent-storage
          volumes:
            - name: nfs-persistent-storage
              persistentVolumeClaim:
                claimName: db-backup-volume