apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: splunk-broker-persistent-data
spec:
  storageClassName: managed-nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
