resources:
- ../base

namespace: monitoring

configMapGenerator:
- literals:
  - RABBITMQ_HOSTS=dev-dcu-rmq1-39.cloud.phx3.gdg:15672,dev-dcu-rmq2-39.cloud.phx3.gdg:15672,dev-dcu-rmq3-39.cloud.phx3.gdg:15672
  - POSTGRESQL_HOSTS=postgres://10.37.117.221:5432?sslmode=disable
  name: env-specific-values
