#!/usr/bin/env ansible-playbook
- name: disable cset user expiration
  hosts: all
  become: yes
  vars_files:
    - vars.yaml
  tasks:
    - name: disable cset user expiration
      ansible.builtin.shell: chage -I -1 -m 0 -M 99999 -E -1 cset
