#!/usr/bin/env ansible-playbook
- name: start the k3s process on the first server node
  hosts: k3sserver[0]
  become: yes
  vars_files:
    - vars.yaml
  tasks:
    - name: Enable and check K3s service
      systemd:
        name: k3s
        daemon_reload: yes
        state: restarted
        enabled: yes