#!/usr/bin/env ansible-playbook
- name: start and enable rabbitmq on all nodes
  hosts: rabbitmq
  become: yes
  vars_files:
    - vars.yaml
  tasks:
    - name: Start and enable the rabbitmq service
      systemd:
        name: rabbitmq-server
        daemon_reload: yes
        state: restarted
        enabled: yes