name: Execute Ansible Playbook
on:
  workflow_dispatch:
    inputs:
      env:
        type: choice
        description: Select deploy env
        required: true
        options:
        - dev
        - prod
      tag:
        description: Select tags
        default: ""
        required: false
      playbook:
        default: site.yaml
        description: playbook to run
        required: true
jobs:
  deploy:
    concurrency: cset-ansible
    runs-on: [csetubuntu]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.11.1
        architecture: 'x64'
    - name: Base python setup/install
      env:
        ANSIBLE_GALAXY_SERVER: https://old-galaxy.ansible.com/
      run: |
        cd ansible
        make ci
    - name: Get dc1 Service account credentials
      id: dc1
      run: |
        SECRET=$(aws secretsmanager get-secret-value --region us-west-2 --secret-id '/KeePass/svc-accounts/dc1-openstack' --query 'SecretString' --output text)
        DC1_USERNAME=$(echo ${SECRET} | jq -r .username)
        DC1_PASSWORD=$(echo ${SECRET} | jq -r .password)
        echo "::set-output name=dc1-user::${DC1_USERNAME}"
        echo "::set-output name=dc1-password::${DC1_PASSWORD}"
        echo "::add-mask::$DC1_USERNAME"
        echo "::add-mask::$DC1_PASSWORD"
    - name: Run Ansible Playbook
      env:
        OS_AUTH_URL: https://phx-prd.openstack.int.gd3p.tools:5000
        OS_PROJECT_DOMAIN_NAME: default
        OS_USER_DOMAIN_NAME: default
        OS_DOMAIN_NAME: default
        OS_PROJECT_NAME: abusepipeline-${{ github.event.inputs.env }}
        OS_AUTH_TYPE: password
        OS_USERNAME: ${{ steps.dc1.outputs.dc1-user }}
        OS_PASSWORD: ${{ steps.dc1.outputs.dc1-password }}
        OS_IDENTITY_API_VERSION: "3"
        AWS_DEFAULT_REGION: us-west-2 
        ANSIBLE_HOST_KEY_CHECKING: False
        ANSIBLE_GALAXY_SERVER: https://old-galaxy.ansible.com/
      run: |
        cd ansible
        TAGS=""
        if [[ "${{ github.event.inputs.tag }}" != "" ]]; then
          TAGS="--tags '${{ github.event.inputs.tag }}'"
        fi
        ansible-playbook ${{ github.event.inputs.playbook }} -e "env=${{ github.event.inputs.env }}" $TAGS -i inventory/${{ github.event.inputs.env }}.ini
