name: Execute Ansible Playbook
on:
  workflow_dispatch:
    inputs:
      env:
        type: choice
        description: Select deploy env
        required: true
        options:
        - dev
      tag:
        type: choice
        description: Select tags
        required: true
        options:
        - mongo
        - k3s
        - rabbitmq
        - bastion
jobs:
  deploy:
    concurrency: cset-ansible
    runs-on: [csetubuntu]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.10.6
        architecture: 'x64'
    - name: Base python setup/install
      run: |
        cd ansible
        make ci
    - name: Get dc1 Service account credentials
      id: dc1
      run: |
        SECRET=$(aws secretsmanager get-secret-value --secret-id '/KeePass/svc-accounts/dc1-openstack' --query 'SecretString' --output text)
        DC1_USERNAME=$(echo ${SECRET} | jq -r .username)
        DC1_PASSWORD=$(echo ${SECRET} | jq -r .password)
        echo "::set-output name=dc1-user::${DC1_USERNAME}"
        echo "::set-output name=dc1-password::${DC1_PASSWORD}"
        echo "::add-mask::$DC1_USERNAME"
        echo "::add-mask::$DC1_PASSWORD"
    - name: Run Ansible Playbook
      env:
        OS_AUTH_URL: https://phx-prd.openstack.int.gd3p.tools:5000
        OS_PROJECT_DOMAIN_NAME: default
        OS_USER_DOMAIN_NAME: default
        OS_DOMAIN_NAME: default
        OS_PROJECT_NAME: abusepipeline-${{ github.event.inputs.env }}
        OS_AUTH_TYPE: password
        OS_USERNAME: ${{ steps.dc1.outputs.dc1-user }}
        OS_PASSWORD: ${{ steps.dc1.outputs.dc1-password }}
        OS_IDENTITY_API_VERSION: "3"
        AWS_DEFAULT_REGION: us-west-2 
        OS_ENDPOINT_OVERRIDE: https://phx-prd.openstack.int.gd3p.tools:8774
      run: |
        cd ansible
        ansible-playbook site.yaml -e "env=${{ github.event.inputs.env }}" --tags "${{ github.event.inputs.tag }}"
