name: Expiring Certs Check
on:
  workflow_dispatch:
  schedule:
    - cron:  '00 17 * * TUE'
jobs:
  expiring-certs-check:
    runs-on: [csetubuntu]
    timeout-minutes: 25
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608
      - name: Get Secrets
        id: secrets
        run: |
          SECRET=$(aws secretsmanager get-secret-value --region us-west-2 --secret-id '/Secrets/slack' --query 'SecretString' --output text)
          SLACK_WEBHOOK_URL=$(echo ${SECRET} | jq -r .webhook)
          echo "::set-output name=slack-webhook-url::${SLACK_WEBHOOK_URL}"
          echo "::add-mask::$SLACK_WEBHOOK_URL"
      - name: Configure kubeconfigs
        run: |
          export AWS_REGION='us-west-2'
          aws secretsmanager get-secret-value --region us-west-2 --secret-id /KeePass/K8s/dev-ng-client.crt | jq -r '.SecretString' > ./.github/static/dev-ng-client.crt
          aws secretsmanager get-secret-value --region us-west-2 --secret-id /KeePass/K8s/dev-ng-client.key | jq -r '.SecretString' > ./.github/static/dev-ng-client.key
          aws secretsmanager get-secret-value --region us-west-2 --secret-id /KeePass/K8s/prod-ng-client.crt | jq -r '.SecretString' > ./.github/static/prod-ng-client.crt
          aws secretsmanager get-secret-value --region us-west-2 --secret-id /KeePass/K8s/prod-ng-client.key | jq -r '.SecretString' > ./.github/static/prod-ng-client.key
      - name: Pull down credentials
        run: |
          export AWS_REGION='us-west-2'
          aws secretsmanager get-secret-value --region us-west-2 --secret-id /KeePass/K8s/p3pabuse01-client.crt | jq -r '.SecretString' > ./.github/static/p3pabuse01-client.crt
          aws secretsmanager get-secret-value --region us-west-2 --secret-id /KeePass/K8s/p3pabuse01-client.key | jq -r '.SecretString' > ./.github/static/p3pabuse01-client.key
      - uses: actions/setup-python@65d7f2d534ac1bc67fcd62888c5f4f3d2cb2b236
        with:
          python-version: 3.11.1
          architecture: 'x64'
      - uses: azure/setup-kubectl@901a10e89ea615cf61f57ac05cecdf23e7de06d8
        with:
          version: 'v1.16.3'
      - name: Results
        run: | 
          export AWS_REGION='us-west-2'
          export USER_NAME=$(aws secretsmanager get-secret-value --region us-west-2 --secret-id /KeePass/svc-accounts/aws-abuse-pipeline | jq --raw-output '.SecretString' | jq -r .username)
          export USER_PASSWORD=$(aws secretsmanager get-secret-value --region us-west-2 --secret-id /KeePass/svc-accounts/aws-abuse-pipeline | jq --raw-output '.SecretString' | jq -r .password)
          chmod +x ${GITHUB_WORKSPACE}/.github/expiring_certs_check.sh && ${GITHUB_WORKSPACE}/.github/expiring_certs_check.sh
        env:
          SLACK_WEBHOOK_URL: ${{ steps.secrets.outputs.slack-webhook-url }}
