name: GCI Image Check
on:
  workflow_dispatch:
  schedule:
    - cron:  '20 14 * * MON'
jobs:
  rebuild-docker-images:
    runs-on: [csetubuntu]
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v2
      - name: Get Secrets
        id: secrets
        run: |
          SECRET=$(aws secretsmanager get-secret-value --region us-west-2 --secret-id '/GitHub/GitHub-Actions-Runner-PAT' --query 'SecretString' --output text)
          PAT=$(echo ${SECRET} | jq -r .PAT)
          echo "::set-output name=pat-cloud::${PAT}"
          echo "::add-mask::$PAT"
          SECRET=$(aws secretsmanager get-secret-value --region us-west-2 --secret-id '/CICD/artifactory' --query 'SecretString' --output text)
          USERNAME=$(echo ${SECRET} | jq -r .username)
          PASSWORD=$(echo ${SECRET} | jq -r .password)
          echo "::set-output name=artifactory-username::${USERNAME}"
          echo "::add-mask::$USERNAME"
          echo "::set-output name=artifactory-password::${PASSWORD}"
          echo "::add-mask::$PASSWORD"

          SECRET=$(aws secretsmanager get-secret-value --region us-west-2 --secret-id '/Secrets/slack' --query 'SecretString' --output text)
          SLACK_WEBHOOK_URL=$(echo ${SECRET} | jq -r .webhook)
          echo "::set-output name=slack-webhook-url::${SLACK_WEBHOOK_URL}"
          echo "::add-mask::$SLACK_WEBHOOK_URL"
      - name: Docker login for Golden Containers ECR
        run: |
          aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 764525110978.dkr.ecr.us-west-2.amazonaws.com
      - name: Docker login for Artifactory
        env:
          ARTIFACTORY_USER: ${{ steps.secrets.outputs.artifactory-username }}
          ARTIFACTORY_PASSWORD: ${{ steps.secrets.outputs.artifactory-password }}
        run: docker login -u ${ARTIFACTORY_USER} -p ${ARTIFACTORY_PASSWORD} gdartifactory1.jfrog.io/docker-dcu-local
      - name: Check and rebuild images
        run: cd containers && ./build.sh
        env:
          SLACK_CHANNEL: ise-oncall-notifications
          SLACK_WEBHOOK_URL: ${{ steps.secrets.outputs.slack-webhook-url }}
          GITHUB_TOKEN: ${{ steps.secrets.outputs.pat-cloud }}