name: Github Stats
on:
  workflow_dispatch:
  schedule:
    - cron:  '25 14 * * MON-FRI'
    - cron:  '25 15-23 * * MON-FRI'
jobs:
  generate-stats:
    runs-on: [csetubuntu]
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
      - name: Get Secrets
        id: secrets
        run: |
          SECRET=$(aws secretsmanager get-secret-value --secret-id '/GitHub/GitHub-Actions-Runner-PAT' --query 'SecretString' --output text)
          PAT=$(echo ${SECRET} | jq -r .PAT)
          echo "::set-output name=pat-cloud::${PAT}"
          echo "::add-mask::$PAT"

          SECRET=$(aws secretsmanager get-secret-value --secret-id '/Secrets/slack' --query 'SecretString' --output text)
          SLACK_WEBHOOK_URL=$(echo ${SECRET} | jq -r .webhook)
          echo "::set-output name=slack-webhook-url::${SLACK_WEBHOOK_URL}"
          echo "::add-mask::$SLACK_WEBHOOK_URL"
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7.10
          architecture: 'x64'
      - name: Install gh cli
        run: |
          curl -L https://github.com/cli/cli/releases/download/v2.7.0/gh_2.7.0_linux_amd64.tar.gz > gh_2.7.0_linux_amd64.tar.gz
          tar xf gh_2.7.0_linux_amd64.tar.gz
          rm gh_2.7.0_linux_amd64.tar.gz
          mkdir -p ~/bin/
          mv gh_2.7.0_linux_amd64/bin/gh ~/bin/
          rm -rf gh_2.7.0_linux_amd64/
      - name: Complete Stats
        if: github.event.schedule == '25 14 * * MON-FRI'
        run: chmod +x ${GITHUB_WORKSPACE}/.github/github_stats.sh && PATH="$PATH:~/bin" ${GITHUB_WORKSPACE}/.github/github_stats.sh -c
        env:
          SLACK_CHANNEL: customer_protection
          SLACK_WEBHOOK_URL: ${{ steps.secrets.outputs.slack-webhook-url }}
          GITHUB_TOKEN: ${{ steps.secrets.outputs.pat-cloud }}
      - name: Hourly Stats
        if: github.event.schedule == '25 15-23 * * MON-FRI' || github.event.schedule != '25 14 * * MON-FRI'
        run: chmod +x ${GITHUB_WORKSPACE}/.github/github_stats.sh && PATH="$PATH:~/bin" ${GITHUB_WORKSPACE}/.github/github_stats.sh -d
        env:
          SLACK_CHANNEL: customer_protection
          SLACK_WEBHOOK_URL: ${{ steps.secrets.outputs.slack-webhook-url }}
          GITHUB_TOKEN: ${{ steps.secrets.outputs.pat-cloud }}