name: Github Stats
on:
  workflow_dispatch:
  schedule:
    - cron:  '15 14 * * MON-FRI'
    - cron:  '15 15-23 * * MON-FRI'
jobs:
  generate-stats:
    concurrency: main
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_CICD }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_CICD }}
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE_CICD }}
          role-duration-seconds: 900
          aws-region: us-west-2
      - name: Complete Stats
        if: github.event.schedule != '15 14 * * MON-FRI'
        run: chmod +x ${GITHUB_WORKSPACE}/.github/github_stats.sh && ${GITHUB_WORKSPACE}/.github/github_stats.sh -c
        env:
          SLACK_CHANNEL: customer_protection
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          GITHUB_TOKEN: ${{ secrets.REPO_PAT }}
      - name: Hourly Stats
        if: github.event.schedule != '15 15-23 * * MON-FRI'
        run: chmod +x ${GITHUB_WORKSPACE}/.github/github_stats.sh && ${GITHUB_WORKSPACE}/.github/github_stats.sh -d
        env:
          SLACK_CHANNEL: customer_protection
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          GITHUB_TOKEN: ${{ secrets.REPO_PAT }}