name: Github Settings
on:
  workflow_dispatch:
jobs:
  sync-settings:
    runs-on: [csetubuntu]
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608
      - name: Get Secrets
        id: secrets
        run: |
          SECRET=$(aws secretsmanager get-secret-value --region us-west-2 --secret-id '/GitHub/GitHub-Actions-Runner-PAT' --query 'SecretString' --output text)
          PAT=$(echo ${SECRET} | jq -r .PAT)
          echo "::set-output name=pat-cloud::${PAT}"
          echo "::add-mask::$PAT"
      - uses: actions/setup-python@65d7f2d534ac1bc67fcd62888c5f4f3d2cb2b236
        with:
          python-version: 3.11.1
          architecture: 'x64'
      - name: Install gh cli
        run: |
          curl -L https://github.com/cli/cli/releases/download/v2.7.0/gh_2.7.0_linux_amd64.tar.gz > gh_2.7.0_linux_amd64.tar.gz
          tar xf gh_2.7.0_linux_amd64.tar.gz
          rm gh_2.7.0_linux_amd64.tar.gz
          mkdir -p ~/bin/
          mv gh_2.7.0_linux_amd64/bin/gh ~/bin/
          rm -rf gh_2.7.0_linux_amd64/
      - name: Github settings sync
        env:
          GITHUB_TOKEN: ${{ steps.secrets.outputs.pat-cloud }}
        run: |
          gh auth setup-git
          git config --global user.email "cset@godaddy.com"
          git config --global user.name "CSET Service Account"
          chmod +x ${GITHUB_WORKSPACE}/.github/github_settings.sh
          PATH="$PATH:~/bin" ${GITHUB_WORKSPACE}/.github/github_settings.sh
