name: GitHub Metrics
on:
  workflow_dispatch:
    inputs:
      dateString:
        description: 'Start date for metrics. Format: YYYY-MM-DD'
        type: string
        required: true
jobs:
  github-metrics:
    runs-on: [csetubuntu]
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.11.1
          architecture: 'x64'
      - uses: azure/setup-kubectl@v3.0
        with:
          version: 'v1.16.3'
      - name: Get Secrets
        id: secrets
        run: |
          SECRET=$(aws secretsmanager get-secret-value --region us-west-2 --secret-id '/GitHub/GitHub-Actions-Runner-PAT' --query 'SecretString' --output text)
          PAT=$(echo ${SECRET} | jq -r .PAT)
          echo "::set-output name=pat-cloud::${PAT}"
          echo "::add-mask::$PAT"

          SECRET=$(aws secretsmanager get-secret-value --region us-west-2 --secret-id '/Secrets/slack' --query 'SecretString' --output text)
          SLACK_WEBHOOK_URL=$(echo ${SECRET} | jq -r .webhook)
          echo "::set-output name=slack-webhook-url::${SLACK_WEBHOOK_URL}"
          echo "::add-mask::$SLACK_WEBHOOK_URL"
      - name: Results
        run:
          chmod +x ${GITHUB_WORKSPACE}/.github/github_metrics.sh && ${GITHUB_WORKSPACE}/.github/github_metrics.sh
        env:
          SLACK_WEBHOOK_URL: ${{ steps.secrets.outputs.slack-webhook-url }}
          INFOSEC_PAT: ${{ steps.secrets.outputs.pat-cloud }}
          DATE_STRING: ${{ github.event.inputs.dateString }}
