name: Outdated Image Check
on:
  workflow_dispatch:
  schedule:
    - cron:  '20 18 * * MON'
jobs:
  scale-out-runner:
    concurrency: main
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout DCU actions
        uses: actions/checkout@v2
        with:
          repository: gdcorp-infosec/dcu-actions
          token: ${{ secrets.REPO_PAT }}
          path: local-actions/dcu-actions
      - name: Scale Runners
        uses: ./local-actions/dcu-actions/scale
        with:
          aws-access-key: ${{ secrets.AWS_ACCESS_KEY_ID_CICD }}
          aws-secret-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_CICD }}
          aws-deploy-role: ${{ secrets.AWS_DEPLOY_ROLE_CICD }}
          repo-pat: ${{ secrets.REPO_PAT }}
  outdated-image-check:
    runs-on: [ec2ubuntu]
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_CICD }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_CICD }}
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE_CICD }}
          role-duration-seconds: 3600
          aws-region: us-west-2
      - name: Pull down credentials
        run: |
          export AWS_REGION='us-west-2'
          aws secretsmanager get-secret-value --secret-id /KeePass/K8s/p3dabuse01-client.crt | jq -r '.SecretString' > ./.github/static/p3dabuse01-client.crt
          aws secretsmanager get-secret-value --secret-id /KeePass/K8s/p3dabuse01-client.key | jq -r '.SecretString' > ./.github/static/p3dabuse01-client.key
          aws secretsmanager get-secret-value --secret-id /KeePass/K8s/p3pabuse01-client.crt | jq -r '.SecretString' > ./.github/static/p3pabuse01-client.crt
          aws secretsmanager get-secret-value --secret-id /KeePass/K8s/p3pabuse01-client.key | jq -r '.SecretString' > ./.github/static/p3pabuse01-client.key
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7.10
          architecture: 'x64'
      - uses: azure/setup-kubectl@v2.0
        with:
          version: 'v1.16.3'
      - name: Docker login for Artifactory
        env:
          ARTIFACTORY_USER: ${{ secrets.ARTIFACTORY_USER }}
          ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
        run: docker login -u ${ARTIFACTORY_USER} -p ${ARTIFACTORY_PASSWORD} docker-dcu-local.artifactory.secureserver.net
      - name: Results
        run: chmod +x ${GITHUB_WORKSPACE}/.github/check_image_updates.sh && ${GITHUB_WORKSPACE}/.github/check_image_updates.sh
        env:
          SLACK_CHANNEL: customer_protection
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
