name: Run secret syncs
on:
  schedule:
    - cron: "0 13 * * 2"
  workflow_dispatch:
jobs:
  sync:
    runs-on: [csetubuntu]
    steps:
      - name: Assume deploy role
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::233599685880:role/GD-AWS-USA-GD-dcuabuse-CICD-Deploy
          role-skip-session-tagging: true
          role-duration-seconds: 3600
          aws-region: us-west-2
      - uses: actions/checkout@v2
      - uses: azure/setup-kubectl@v2.0
        with:
          version: 'v1.24.4'
      - name: Configure kubeconfigs
        run: |
          aws secretsmanager get-secret-value --secret-id /KeePass/K8s/dev-ng-client.crt | jq -r '.SecretString' > ./.github/static/dev-ng-client.crt
          aws secretsmanager get-secret-value --secret-id /KeePass/K8s/dev-ng-client.key | jq -r '.SecretString' > ./.github/static/dev-ng-client.key
      - name: Get Secrets
        id: secrets
        run: |
          SECRET=$(aws secretsmanager get-secret-value --secret-id '/GitHub/GitHub-Actions-Runner-PAT' --query 'SecretString' --output text)
          PAT=$(echo ${SECRET} | jq -r .PAT)
          echo "::set-output name=pat-cloud::${PAT}"
          echo "::add-mask::$PAT"
      - name: Get JOMAX Service account credentials
        id: jomax
        run: |
          SECRET=$(aws secretsmanager get-secret-value --secret-id '/KeePass/svc-accounts/aws-abuse-pipeline' --query 'SecretString' --output text)
          JOMAX_USERNAME=$(echo ${SECRET} | jq -r .username)
          JOMAX_PASSWORD=$(echo ${SECRET} | jq -r .password)
          echo "::set-output name=jomax-user::${JOMAX_USERNAME}"
          echo "::set-output name=jomax-password::${JOMAX_PASSWORD}"
          echo "::add-mask::$JOMAX_USERNAME"
          echo "::add-mask::$JOMAX_PASSWORD"
      - name: Get SSO token for jomax service account
        id: sso-token
        run: |
          while [[ -z "$SSO_RESPONSE" ]]
          do
              SSO_RESPONSE=`curl -X POST https://sso.godaddy.com/v1/api/token -H 'Content-Type: application/json' -d '{"username":"${{ steps.jomax.outputs.jomax-user }}","password":"${{ steps.jomax.outputs.jomax-password }}","realm":"jomax"}'`
              echo ${SSO_RESPONSE}
              if [[ -z "${SSO_RESPONSE}" ]]; then sleep 1; fi
          done
          SSO_TOKEN=`echo $SSO_RESPONSE | jq -r .data`
          echo "::set-output name=sso-token::$SSO_TOKEN"
          echo "::add-mask::$SSO_TOKEN"
      - name: Checkout SSL Action Repo
        uses: actions/checkout@v2
        with:
          repository: gdcorp-actions/ssl-action
          path: ./ssl-action
          token: ${{ steps.secrets.outputs.pat-cloud }}
      - name: Sync PostgreSQL Beat Credentials
        env:
          AWS_REGION: us-west-2
        run: |
          export KUBECONFIG=$PWD/.github/static/ng-config.yml
          SECRET=$(aws secretsmanager get-secret-value --secret-id '/KeePass/ProductionPostgreSQLMetricbeat' --query 'SecretString' --output text)
          USER=$(echo ${SECRET} | jq -r .user)
          PASS=$(echo ${SECRET} | jq -r .password)
          echo "::add-mask::$USER"
          echo "::add-mask::$PASS"

          kubectl --context=dev-ng -n monitoring create secret generic postgresql-secrets --from-literal=username="$USER" --from-literal=password="$PASS" --dry-run -o yaml | kubectl --context=dev-ng apply -f -
          kubectl --context=dev-ng delete pod -l k8s-app=metricbeat -n monitoring
      - name: Sync MongoDB Beat Credentials
        env:
          AWS_REGION: us-west-2
        run: |
          export KUBECONFIG=$PWD/.github/static/ng-config.yml
          SECRET=$(aws secretsmanager get-secret-value --secret-id '/KeePass/MongoDB/phishstory/dev/metricbeat' --query 'SecretString' --output text)
          URL=$(echo ${SECRET} | jq -r .url)
          echo "::add-mask::$URL"

          kubectl --context=dev-ng -n monitoring create secret generic mongodb-metricbeat --from-literal=url="$URL" --dry-run -o yaml | kubectl --context=dev-ng apply -f -
          kubectl --context=dev-ng delete pod -l k8s-app=metricbeat -n monitoring
      - name: Sync RabbitMQ Beat Credentials
        env:
          AWS_REGION: us-west-2
        run: |
          export KUBECONFIG=$PWD/.github/static/ng-config.yml
          SECRET=$(aws secretsmanager get-secret-value --secret-id '/KeePass/tools/rabbitmq-console' --query 'SecretString' --output text)
          USER=$(echo ${SECRET} | jq -r .username)
          PASS=$(echo ${SECRET} | jq -r .password)
          echo "::add-mask::$USER"
          echo "::add-mask::$PASS"

          kubectl --context=dev-ng -n monitoring create secret generic rabbitmq-secrets --from-literal=username="$USER" --from-literal=password="$PASS" --dry-run -o yaml | kubectl --context=dev-ng apply -f -
          kubectl --context=dev-ng delete pod -l k8s-app=metricbeat -n monitoring
      - name: Create/Renew rmq certs
        uses: ./ssl-action
        with:
          command: import-secrets
          certificates: '[{"server":"*.rmq.cset.int.dev-gdcorp.tools","allow_renewal":true}]'
          team: ENG-DCU
          renew: true
          sso_token: ${{ steps.sso-token.outputs.sso-token }}
          renewal_days: 90
      - name: Create/Renew mongodb production client cert
        uses: ./ssl-action
        with:
          command: import-secrets
          certificates: '[{"client":"client.mongodb.cset.int.godaddy.com","allow_renewal":true,"issuer_validation": "SSL"}]'
          team: ENG-CSET
          renew: true
          sso_token: ${{ steps.sso-token.outputs.sso-token }}
          renewal_days: 90

